spring:
  jpa:
    show-sql: false
  flyway:
    validate-on-migrate: true

app:
  kafka:
    enabled: ${KAFKA_ENABLED:false}

simulator:
  enabled: ${SIMULATOR_ENABLED:false}

storage:
  s3:
    enabled: ${STORAGE_S3_ENABLED:false}

logging:
  level:
    com.droneiq: INFO
    org.springframework: WARN
    org.apache.kafka: ERROR
