spring:
  jpa:
    show-sql: false
  flyway:
    validate-on-migrate: true

simulator:
  enabled: false

storage:
  s3:
    enabled: true

logging:
  level:
    com.droneiq: INFO
    org.springframework: WARN
    org.apache.kafka: WARN
